add_subdirectory(CloneCore)
add_subdirectory(OperationCore)
add_subdirectory(MigrationCore)
add_subdirectory(DiskModel)
add_subdirectory(ImageFormat)
add_subdirectory(VssRequester)
add_subdirectory(BootRepair)
add_subdirectory(WindowsShrinkAnalysis)
add_subdirectory(WindowsDism)
add_subdirectory(MigrationEngine)
add_subdirectory(MediaBuilder)
add_subdirectory(UiSupport)
add_subdirectory(WindowsApp)
add_subdirectory(DirectShrinkTarget)
add_subdirectory(CliTools)
add_subdirectory(WinPEApp)
